"""add ai insight columns to books

Revision ID: 6b38221cef21
Revises: ecf2d0e06d18
Create Date: 2026-08-13 04:19:03.977741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b38221cef21'
down_revision: Union[str, None] = 'ecf2d0e06d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('books', sa.Column('ai_key_takeaways', sa.JSON(), nullable=True))
    op.add_column('books', sa.Column('ai_target_audience', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'ai_target_audience')
    op.drop_column('books', 'ai_key_takeaways')
    op.drop_column('books', 'ai_summary')
    # ### end Alembic commands ###
